- name: PLAY-1 Catalogue installation
  hosts: catalogue
  become: yes
  tasks:
  - name: PLAY-1 TASK-1 disable nodejs default version
    command: dnf module disable nodejs -y

  - name: PLAY-1 TASK-2 enable nodejs:18
    command: dnf module enable nodejs:18 -y

  - name: PLAY-1 TASK-2 nodejs:18 installation
    ansible.builtin.package:
      name: nodejs
      state: present


      