- name: PLAY-1 Catalogue installation
  hosts: catalogue
  become: yes
  tasks:
  - name: PLAY-1 TASK-13 Data load existance check
    ansible.builtin.command: mongo --host mongodb.hellodns.xyz --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
    register: load_output
    
  - name: PLAY-1 TASK-14 Data load if not exists
    ansible.builtin.debug:
      msg: "output is: {{load_output}}"







      