- name: Mysql Installation
  hosts: mysql
  become: yes
  vars:
    password: RoboShop@1
  tasks:
  - name: PLAY-1 TASK-1 Disabling default mysql version
    ansible.builtin.command: dnf module disable mysql -y

  - name: PLAY-1 TASK-2 Setup the MySQL5.7 repo file
    ansible.builtin.copy:
      src: mysql.repo
      dest: /etc/yum.repos.d/mysql.repo

  - name: PLAY-1 TASK-3 Install MySQL Server
    ansible.builtin.package:
      name: mysql-community-server
      state: present

  - name: PLAY-1 TASK-4 Enable and Start MySQL Service
    ansible.builtin.systemd:
      name: mysqld
      enabled: yes
      state: started

  - name: PLAY-1 TASK-5 Password Setup
    ansible.builtin.command: mysql_secure_installation --set-root-pass {{password}}
