- name: Rabbit-mq Installation
  hosts: rabit-mq
  become: yes
  tasks: 
  - name: Configure YUM Repos from the script provided by vendor.
    ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

  - name: Configure YUM Repos for RabbitMQ.
    ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

  - name: Install RabbitMQ
    ansible.builtin.dnf:
      name: rabbitmq-server
      state: present

  - name: Enable and Start RabbitMQ Service
    ansible.builtin.systemd:
      name: rabbitmq-server
      enabled: yes
      state: started

  - name: username and password
    ansible.builtin.command: rabbitmqctl add_user roboshop roboshop123

  - name: Permissions
    ansible.builtin.command: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"